### PR TITLE
Update item class

### PR DESCRIPTION
**Pull request by mazx4960**
# Changes
- `setQuantity` function
- `increment` function
- `decrement` function

# Related Issues/ PRs
- None

### CODE REVIEW

**Comment by MechFroG88** [comment]
Will `setQuantity()` be implemented in this pr?

**Comment by mazx4960** [comment]
> Will `setQuantity()` be implemented in this pr?

Yes, but i was thinking maybe can also include a plus and minus beside the item to just increase/ decrease by 1

**Comment by MechFroG88** [comment]
> Yes, but iIwas thinking maybe can also include a plus and minus beside the item to just increase/ decrease by 1

That will be great! I can try to implement it in the UI

**Review by MechFroG88 — APPROVED** [review]

**Review by DavidTan0527 — APPROVED** [review]
LGTM

**Pull request merged**
