### PR TITLE
Update Implementation section of developer guide

### PR DESCRIPTION
**Pull request by 1001mei**
# Changes
- Update the explanations of implementations of feature undo/redo

# Related Issues/ PRs
- None

### CODE REVIEW

**Review by MechFroG88 — COMMENTED** [review]
In diagrams/SaveChangesActivityDiagram. 
I think the branching condition is not stated clearly enough.
Maybe can change it to something like `isSaveChanges?`

**Comment by MechFroG88** [comment]
I think we can also modify the styling for the sequence diagram in future. Cause it looks kinda ugly now haha

**Comment by 1001mei** [comment]
> In diagrams/SaveChangesActivityDiagram. I think the branching condition is not stated clearly enough. Maybe can change it to something like `isSaveChanges?`

okay, maybe change it to `has changes to save`?

**Comment by 1001mei** [comment]
> I think we can also modify the styling for the sequence diagram in future. Cause it looks kinda ugly now haha

Yes, I agree. Will open an issue for that.

**Comment by MechFroG88** [comment]
Do you think that `hasChange` is sufficient?

**Comment by 1001mei** [comment]
> Do you think that `hasChanges` is sufficient? or maybe `hasUnsavedChanges`

Ya, I think `hasChanges` is good. Let's go with this.

**Review by MechFroG88 — APPROVED** [review]

**Pull request merged**
