### PR TITLE
Implement undo-redo feature

### LINKED ISSUE #80: [Feature Request] Undo Command
Allow users to undo last command.

This could be implemented by saving the states of the model after each command executed

### PR DESCRIPTION
**Pull request by 1001mei**
# Changes
- [x] Add commands for undo and redo
- [x] Make product commands(`add`, `update`, `delete`) reversible
- [x] Make item commands(`add`, `update`, `delete`) reversible
- [x] Make `clear` command reversible
- [x] Make update-all and delete-all commands reversible
- [x] Add unit tests

# Related Issues/ PRs
- Fixes #80

### CODE REVIEW

**Review by DavidTan0527 — COMMENTED** [review]
Great work at implementing the features. Just a few comments:
### 1. Reorganizing folder structure
Perhaps groups the actions under an appropriate package in model? It might make the project structure easier to understand.

### 2. "Setup and Teardown" methods in `model`
#### Context
I've noticed that `model.prepareIBookForChanges()` and `model.saveIBookChanges()` surround the methods that let commands change the model.

#### Concern
The current design requires the programmer to "remember" to call those methods and doesn't explicitly enforce it.

#### Possible solution
Here, I'll suggest a possible solution (there is most likely a better one):
1. Maintain internal state in `StateChangeRecorder` such that a new `prepareNewStateChange()` cannot be invoked before a previous `saveStateChange()` is executed.
2. Model actions require `prepareNewStateChange()` to be called (without a closing `saveStateChange()`)

Let me know if I've missed out edge cases of misimplementation :D

**Comment by 1001mei** [comment]
# 1. Reorganizing folder structure
That's a good idea. Will group all `ReversibleIBookAction` classes into a new package.

# 2. "Setup and Teardown" methods in `model`
This is a valid concern also. 

Thanks for the proposed solution! 
Just to clarify, so you are suggesting that `saveStateChange()` to be called internally each time before a new `prepareNewStateChange()`?

**Comment by DavidTan0527** [comment]
> ... Just to clarify, so you are suggesting that `saveStateChange()` to be called internally each time before a new `prepareNewStateChange()`?

Actually, I was thinking like a `boolean hasPendingChanges` in `StateChangeRecorder` such that:
1. Actions will check to make sure `hasPendingChanges == true`
2. `saveStateChange()` will set `hasPendingChanges` to `false`
3. `prepareNewStateChange()` only works if `hasPendingChange == false`, sets `hasPendingChange` to `true`

**Comment by DavidTan0527** [comment]
> Okay, I get it now, but when should `saveStateChange()` be called? Everytime before `prepareNewStateChange()`?

It should be called after `prepareNewStateChange()`. But I don't think there is a good way to make this work, so the suggestion I gave just makes sure it is called before the next `prepareNewStateChange()`

Usage-wise it is the same, so no need to change your existing code. I'm just suggesting a defensive strategy to prevent misuses in the future

**Review by DavidTan0527 — APPROVED** [review]

**Pull request merged**
