### PR TITLE
Update various docs

### PR DESCRIPTION
**Pull request by 1001mei**
# Changes
- [x] Update `index.md`
- [x] Restructure user guide

# Related Issues/ PRs
- None

### CODE REVIEW

**Review by MechFroG88 — COMMENTED** [review]
Shall we also include the template for each command?

For example,
```
#### 3.1.2 Adding a product :

##### GUI

##### Command
```

**Review by DavidTan0527 — APPROVED** [review]
LGTM

**Comment by 1001mei** [comment]
> Shall we also include the template for each command?

I was thinking just follow the existing format first, then we only update them to contain GUI screenshots and remarks in next iteration.

**Comment by MechFroG88** [comment]
Sure let's merge it then

**Pull request merged**
